name: Deploy Static Site
description: Build and deploy a static site via rsync + Caddy
inputs:
  host:
    required: true
    description: SSH host
  username:
    required: true
    description: SSH username
  key:
    required: true
    description: SSH private key
  target_dir:
    required: true
    description: Remote directory to deploy to
  node_version:
    required: false
    default: '24'
  pnpm_version:
    required: false
    default: ''
  build_command:
    required: false
    default: 'pnpm build'
  output_dir:
    required: false
    default: 'out'
  skip_build:
    required: false
    default: 'false'
    description: Skip Node/pnpm install and build; deploy source_dir as-is (for plain static sites)
  source_dir:
    required: false
    default: '.'
    description: Directory to deploy when skip_build is true (default repo root)
  reload_caddy:
    required: false
    default: 'false'
    description: Reload Caddy after deploy (requires NOPASSWD sudoers entry)
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - id: detect-pnpm-version
      if: inputs.skip_build != 'true'
      shell: bash
      run: |
        VERSION="${{ inputs.pnpm_version }}"
        
        if [ -z "$VERSION" ] && [ -f "package.json" ]; then
          if grep -q '"packageManager"[[:space:]]*:[[:space:]]*"pnpm' package.json; then
            echo "Detected pnpm in packageManager, letting pnpm/action-setup handle it."
            VERSION=""
          else
            VERSION="latest"
          fi
        elif [ -z "$VERSION" ]; then
          VERSION="latest"
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "use_package_manager=$([ -z "$VERSION" ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
    - uses: pnpm/action-setup@v4
      if: inputs.skip_build != 'true' && steps.detect-pnpm-version.outputs.use_package_manager != 'true'
      with:
        version: ${{ steps.detect-pnpm-version.outputs.version }}
    - uses: pnpm/action-setup@v4
      if: inputs.skip_build != 'true' && steps.detect-pnpm-version.outputs.use_package_manager == 'true'
    - uses: actions/setup-node@v4
      if: inputs.skip_build != 'true'
      with:
        node-version: ${{ inputs.node_version }}
        cache: pnpm

    - name: Install dependencies
      if: inputs.skip_build != 'true'
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Build
      if: inputs.skip_build != 'true'
      run: ${{ inputs.build_command }}
      shell: bash

    - name: Deploy via rsync
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: ${{ inputs.skip_build == 'true' && '--exclude=.git --exclude=.github ' || '' }}-avzr --delete --checksum
        path: ${{ inputs.skip_build == 'true' && inputs.source_dir || inputs.output_dir }}/
        remote_path: ${{ inputs.target_dir }}
        remote_host: ${{ inputs.host }}
        remote_user: ${{ inputs.username }}
        remote_key: ${{ inputs.key }}

    - name: Reload Caddy
      if: ${{ inputs.reload_caddy == 'true' }}
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        script: |
          sudo systemctl reload caddy