name: Deploy Docker Compose App
description: Build and restart services using docker compose on VPS
inputs:
  host:
    required: true
    description: "SSH host address"
  username:
    required: true
    description: "SSH username"
  key:
    required: true
    description: "SSH private key"
  project_dir:
    required: true
    description: "Absolute path to project directory on host"
  compose_file:
    required: false
    default: "docker-compose.yml"
    description: "Path to the compose file relative to project_dir"
  migration_service:
    required: false
    default: ""
    description: "Service name to run migrations on (leave empty to skip)"
  migration_command:
    required: false
    default: ""
    description: "Full migration command to run (e.g. 'npx prisma migrate deploy')"
runs:
  using: composite
  steps:
    - uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        script: |
          set -e
          export DOCKER_HOST=unix:///run/user/1000/docker.sock
          export XDG_RUNTIME_DIR=/run/user/1000

          cd "${{ inputs.project_dir }}"

          git fetch origin
          git reset --hard origin/main

          docker compose -f ${{ inputs.compose_file }} pull
          docker compose -f ${{ inputs.compose_file }} up -d --build --remove-orphans

          if [ -n "${{ inputs.migration_service }}" ] && [ -n "${{ inputs.migration_command }}" ]; then
            echo "Waiting for ${{ inputs.migration_service }} to be healthy..."
            docker compose -f ${{ inputs.compose_file }} wait ${{ inputs.migration_service }}
            docker compose -f ${{ inputs.compose_file }} exec -T ${{ inputs.migration_service }} ${{ inputs.migration_command }}
          else
            echo "Skipping migrations"
          fi

          docker image prune -af