name: Deploy Docker Compose App
description: Build and restart services using docker compose on VPS
inputs:
  host: { required: true }
  username: { required: true }
  key: { required: true }
  project_dir: { required: true }
  compose_file:
    required: false
    default: "docker-compose.yml"
    description: "Path to the compose file if different"
  migration_service:
    required: false
    default: "api"
    description: "Service name to run migrations on"
runs:
  using: composite
  steps:
    - uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        script: |
          set -e
          target_dir="${{ inputs.project_dir }}"
          
          # 1. Navigate to project
          cd "$target_dir"
          
          # 2. Update Code
          git fetch origin
          git reset --hard origin/main
          
          # 3. Docker Compose Deploy
          docker compose -f ${{ inputs.compose_file }} pull
          docker compose -f ${{ inputs.compose_file }} up -d --build --remove-orphans
          
          # 4. Run Migrations (wait for containers to be healthy)
          echo "Waiting for services to be ready..."
          sleep 5
          docker compose -f ${{ inputs.compose_file }} exec -T ${{ inputs.migration_service }} npx prisma migrate deploy
          
          # 5. Prune
          docker image prune -af
